<?php
/*
 * 基础设置
 */
return [
    "siteRoot" => 'http://www.eopark.com',
    "sitePath" => 'eopark.com',
    "siteChineseName" => "EOPARK",
    "siteEnglishName" => "EOPARK",
    "siteLogo" => "/img/logo_black.png",
    "siteBeian" => "蜀ICP备16032292号",
    "siteEmail" => "123456",
    "siteSlogan" => "",

    "httpHost" => $_SERVER['SERVER_NAME'],
    "documentRoot" => $_SERVER["DOCUMENT_ROOT"],
    "resourceType" => array(
        0 => "其他",
        1 => "视频",
        2 => "图文",
        3 => "下载",
    ),
    'adminUserName' => 'admin',
    'adminPassword' => 'qskane',

    "defaultIndexNev" => array(
        array(
            "id" => 0,
            "url_name" => "百度贴吧",
            "url" => "http://tieba.baidu.com/",
            "x" => 0,
            "y" => 0,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "新浪微博",
            "url" => "http://weibo.com/",
            "x" => 2,
            "y" => 0,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "淘宝网",
            "url" => "http://taobao.com",
            "x" => 4,
            "y" => 0,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "京东商城",
            "url" => "http://jd.com",
            "x" => 6,
            "y" => 0,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "爱奇艺",
            "url" => "http://iqiyi.com",
            "x" => 8,
            "y" => 0,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "优酷视频",
            "url" => "http://youku.com",
            "x" => 10,
            "y" => 0,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "豆瓣",
            "url" => "http://douban.com",
            "x" => 0,
            "y" => 1,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "今日头条",
            "url" => "http://toutiao.com",
            "x" => 2,
            "y" => 1,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "凤凰网",
            "url" => "http://www.ifeng.com/",
            "x" => 4,
            "y" => 1,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "网易新闻",
            "url" => "http://news.163.com/",
            "x" => 6,
            "y" => 1,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "AcFun",
            "url" => "http://acfun.cn",
            "x" => 8,
            "y" => 1,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "知乎",
            "url" => "https://www.zhihu.com/explore",
            "x" => 10,
            "y" => 1,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "汽车之家",
            "url" => "http://autohome.com",
            "x" => 0,
            "y" => 2,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "斗鱼TV",
            "url" => "http://douyu.com",
            "x" => 2,
            "y" => 2,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "4399",
            "url" => "http://www.4399.com/",
            "x" => 4,
            "y" => 2,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "糗事百科",
            "url" => "http://www.qiushibaike.com/",
            "x" => 6,
            "y" => 2,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "暴走漫画",
            "url" => "http://baozoumanhua.com/",
            "x" => 8,
            "y" => 2,
            "width" => 2,
            "height" => 1,
        ),
        array(
            "id" => 0,
            "url_name" => "17173",
            "url" => "http://www.17173.com/",
            "x" => 10,
            "y" => 2,
            "width" => 2,
            "height" => 1,
        ),
    )

    //http://www.htmleaf.com/jQuery/Layout-Interface/201505171847.html
];